# font_size 20
font_family JetBrainsMono NF
bold_font JetBrainsMono NF Bold
italic_font JetBrainsMono NF ExtraLight Italic
bold_italic_font JetBrainsMono NF Bold Italic
# font_family FiraCode Nerd Font Mono
# bold_font FiraCode Nerd Font Mono Bold
# italic_font FiraCode Nerd Font Light

# italic_font JetBrains Mono Italic
# bold_italic_font JetBrains Mono Bold Italic

# italic_font SpaceMono Nerd Font Italic
# bold_italic_font SpaceMono Nerd Font Bold Italic
